### ISSUE TITLE
ERR wrong number of arguments for 'srem' command  

### ISSUE THREAD

**Issue by wslsq** [wan3574489/laravel-websocket#2]
你好，学习并使用了您的代码，
 在按照教程配置好以后启动运行，报错
`ERR wrong number of arguments for 'srem' command  `

redis是4.0.0，laravel5.4+centos7+nginx+swoole
我自己能力暂时无法解决，在此求大神帮忙~十分感谢！

**Comment by wslsq** [comment]
附上laravel.log
[laravel.log.txt](https://github.com/wan3574489/laravel-websocket/files/1151190/laravel.log.txt)

**Comment by wan3574489** [comment]
1.先在服务器上安装php的  Redis扩展，运行命令pecl install redis 。
2.然后将修改laravel框架的redis配置，修改文件/config/database.php文件，将redis 的客户端类库修改为phpredis ,即可修复：
`'redis' => [

        'client' => 'phpredis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],`

**Comment by wslsq** [comment]
非常感谢~之前用的是predis，改成php扩展就可以了。
