### ISSUE TITLE
连接了一段时间就连不上

### ISSUE THREAD

**Issue by wslsq** [wan3574489/laravel-websocket#3]
不好意思我再来打扰了。
通过php artisan Chat:Start启动以后，使用一段时间就不能链接了，提示handshake  timed out。

进程还在，端口也在用，没有报错。

实在不知道会有什么原因，故来请教一下，谢谢~

**Comment by wan3574489** [comment]
不好意思才看到，是已经解决了问题了吗？

**Comment by wslsq** [comment]
@wan3574489 如果并发几次，就会返回一些奇怪的数据，然后没法用了。
返回类似:1  :2的数据。

并发也不多，一个用户多次发送请求就挂掉了。

**Comment by wslsq** [comment]
自己的代码逻辑检查过是没问题的，应该是进程关闭什么的没处理好

**Comment by wan3574489** [comment]
你是不是用的一个页面开了很多个websocket测试的？

**Comment by wslsq** [comment]
@wan3574489 是，这是其中之一。
还有别的情况也会出错，正在观察。。。

**Comment by wan3574489** [comment]
别的情况是指什么？ 我在测试的时候使用一个页面打开多个websocket会出现你说的错误，但是开多个tab页就没有问题。

**Comment by wslsq** [comment]
@wan3574489 不好意思，我还在观察，还不能明确的说是什么问题。

目前还发现的一个就是

我的逻辑代码，有一处从redis读取数据的，
如果请求发送频繁（秒级，真的不多请求）  就会读取不了，然后报错。
redis在同服务器内，性能没有问题。

**Comment by wan3574489** [comment]
能把错误发出来一下吗？

**Comment by wslsq** [comment]
@wan3574489 
[2017-07-23 21:47:21] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: unserialize(): Error at offset 0 of 2 bytes in /data/wwwroot/vgamer.im/app/Http/Controllers/AccountController.php:779
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'unserialize(): ...', '/data/wwwroot/v...', 779, Array)
#1 /data/wwwroot/vgamer.im/app/Http/Controllers/AccountController.php(779): unserialize(':5')
#2 /data/wwwroot/vgamer.im/app/Server/Chat/ChatHandle.php(478): App\Http\Controllers\AccountController::getUserInfo(5, Array)
#3 /data/wwwroot/vgamer.im/vendor/lactone/laravel-websocket/src/ServerHandle.php(136): App\Server\Chat\ChatHandle->message_login(50, Array)


此处我从ChatHandle.php的message_login方法调用AccountController.php里从redis读取用户信息的方法，

正确读取的数据应该是一段序列化数据。
可以看到，redis莫名其妙的把:5存进去了，unserialize(':5')时导致出错。

而我自己的代码不可能把:5存到redis的。

**Comment by wslsq** [comment]
一个页面只开了一个websocket，如果发送多次请求就返回错误信息了。而且返回的速度很慢。
虽然实际使用不会发送那么快的请求，但是有时候秒级的请求也会出现:1,:2的情况。

![qq 20170724145819](https://user-images.githubusercontent.com/12254744/28511616-9890ddce-7080-11e7-8ac6-d9ceac538b62.png)

**Comment by wan3574489** [comment]
swoole的版本是多少？我调试一下

**Comment by wslsq** [comment]
@wan3574489  swoole2.0.8,貌似是最新版。php7.1.4

**Comment by wan3574489** [comment]
好的

**Comment by wslsq** [comment]
@wan3574489 我改成使用普通方法，不使用您的扩展就不会出那个问题了。
粗鲁估计是您的队列处理有问题。因为我的业务比较敢时间，我暂时先用普通方法。
您的扩展代码结构比较优雅，希望能尽早解决，我再用上，谢谢~

**Comment by wan3574489** [comment]
问题产生的主要原因是因为在多进程下使用了同一个Redis链接，当请求数上来后多个进程使用同一个连接就会出现"+ok"和":1"这样的数据，这些数据是Redis协议中存在的特定字符。我修改了代码，解决了Redis出错的问题，目前已经可以正常使用，后续会将DB connection修改掉。   你在使用普通方法的时候也要注意多个进程使用同一链接的问题。

**Comment by WongMinHo** [comment]
@wan3574489 你好，我想请教一下你是如何解决多个进程使用同一链接的问题？因为我也遇到这种情况了。

**Comment by wan3574489** [comment]
@WongMinHo 用了一个比较取巧的方式，我为每个进程生成了一个链接，并不是多个进程使用同一个链接。

`    public function connection($name = null)`
`    {`
`        $name = $name ?: 'default';`
`        $pid_name =getmypid()."_".$name;`
`        if (isset($this->connections[$pid_name])) {`
`            return $this->connections[$pid_name];`
`        }`
`        return $this->connections[$pid_name] = $this->resolve($name);`
`    }`


[具体实现](https://github.com/wan3574489/laravel-websocket/blob/master/src/Redis/RedisManagerCli.php)

**Comment by WongMinHo** [comment]
知道了，谢谢~

**Comment by WongMinHo** [comment]
@wan3574489 知道了，谢谢~
